### PR TITLE
Feature/work/case-study-pages

### PR DESCRIPTION
**Pull request by spark-at-speer**
JIRA Ticket: https://speertech.atlassian.net/browse/SPEERWEB-41

TODO:
- Add transition animations
  - [Defient Section 02](https://speertech.atlassian.net/browse/SPEERWEB-43)
  - [Defient Section 03](https://speertech.atlassian.net/browse/SPEERWEB-44)
  - [Manzil Section 02](https://speertech.atlassian.net/browse/SPEERWEB-48)
  - [Manzil Section 03](https://speertech.atlassian.net/browse/SPEERWEB-49)
- Improve positioning for reviews container
- Add transparency to last image for Defient
- Add transparency to last image for Manzil

### CODE REVIEW

**Comment by rhys-at-speer** [comment]
@spark-at-speer I noticed some of your TODOs were partner specific. Ideally this will be setup such that we simply can swap out images and text for different partnerships, rather than hand crafting a new page for each. Is that something your current implementation accommodates?

**Comment by spark-at-speer** [comment]
> @spark-at-speer I noticed some of your TODOs were partner specific. Ideally this will be setup such that we simply can swap out images and text for different partnerships, rather than hand crafting a new page for each. Is that something your current implementation accommodates?

Yes, I am using a .json file to store the case study data. It is a similar system used for the blog posts.

Each section has properties:
image

And each section has a components array.
The components are rendered in the order they are stored in the array and will render based on their type:
image

**Comment by spark-at-speer** [comment]
Do you think we can get this PR merged? I can create backlog tickets for the remaining items in the TODO.

**Comment by rhys-at-speer** [comment]
> Do you think we can get this PR merged? I can create backlog tickets for the remaining items in the TODO.
> @rhys-at-speer

Sure, sounds good.

**Review by rhys-at-speer — APPROVED** [review]

**Pull request merged**
